services:
  kritikapi:
    container_name: kritikapi
    dns:
      - 1.1.1.1
      - 1.0.0.1
    build: .
    image: hansputera/smantikritikapi
    ports:
      - "5130:5130"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kritikDatabases:/app/databases:rw
    env_file:
      - .env
    restart: "unless-stopped"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5130/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  kritikDatabases: